name: S3 deploy with cloud front

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      # - uses: actions/checkout@v2

      # - name: Use Node.js v18.17.1
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 18.17.1

      # - name: Install dependencies
      #   run: npm install

      # - name: Build
      #   run: npm run build

      # - name: Deploy
      #   uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --exclude '.git/*' # 이 부분은 필요에 따라 수정할 수 있습니다
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload /build to S3
        env:
          BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME}}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://$BUCKET_NAME
